name: Test Workflow
env:
  TEST: this is a test variable

on:
  push:
  schedule:
    - cron: "00 00 * * *"

jobs:
  job_1:
    runs-on: macos-latest
    name: Testing
    steps:
      - name: Test step
        shell: bash
        run: |
              echo "First step"
      - name: Get commits save as var
        shell: bash
        run: |
              curl -sL -u username:${{ secrets.GITHUB_TOKEN }} "https://api.github.com/repos/$GITHUB_REPOSITORY/commits?since=`date -v -1d -u +'%FT%T.%2Z'`" > $HOME/commit.json
              echo $(head -n 10 $HOME/commit.json)
              numcommits="$(jq '. | length' $HOME/commit.json)"
              echo "Number of commits : $numcommits"
              if [ $numcommits -gt 0 ]; then
                echo ::set-env name=UPDATES::true
              fi
      - name:  Test updates var
        if:    env.UPDATES == 'true'
        run:   echo "This is where we will send command to Netlify"
        shell: bash
