name: Test Workflow
env:
  TEST: this is a test variable

on:
  schedule:
    - cron: "* * * * *"

jobs:
  job_1:
    runs-on: ubuntu-latest
    name: Get Date Yesterday
    steps:
      - name: Set date
        shell: bash
        run: |
          echo date -u +'%FT%T.%2NZ' -d "yesterday"
  
