name: Monitor for updates
env:
  TEST: this is a test variable

on:
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  set_new_commits:
    runs-on: ubuntu-latest
    name: Make artifact indicating repo changes
    steps:
      - name: Set new_commits value to true
        shell: bash
        run: |
          "TRUE" > new_commits.txt
      - name: Upload the new commits artifact
        uses: actions/upload-artifact@v1
        with:
          name: new_commits
          path: new_commits.txt
