name: Test Workflow
env:
  TEST: this is a test variable

on:
  schedule:
    - cron: "* * * * *"

jobs:
  job_1:
    runs-on: macos-latest
    name: Get Date Yesterday
    steps:
      - name: Set date
        shell: bash
        run: |
          date -v -1d -u +'%FT%T.%2NZ' 
  
