name: Test Workflow
env:
  TEST: this is a test variable

on:
  push:
  schedule:
    - cron: "00 00 * * *"

jobs:
  job_1:
    runs-on: macos-latest
    name: Testing
    steps:
      - uses: octokit/request-action@v2.x
        id: get_commits
        with:
          route: GET /repos/:repository/commits
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "fromJson(steps.get_commits.outputs.data)"
      - run: "jq '. | length' fromJson(steps.get_commits.outputs.data)"
      - name: See if the date command works
        shell: bash
        run: |
          date -v -1d -u +'%FT%T.%2NZ'
  
