name: Test Workflow
env:
  TEST: this is a test variable

on:
  push:
  schedule:
    - cron: "00 00 * * *"

jobs:
  job_1:
    runs-on: macos-latest
    name: Testing
    steps:
      - uses: octokit/request-action@v2.x
        id: get_commits
        with:
          route: GET /repos/:repository/commits
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "${{ fromJson(steps.get_commits.outputs.data) }}" > $HOME/commit.json
          echo $(head -n 10 $HOME/commit.json)
              numcommits="$(jq '. | length' $HOME/commit.json)"
              echo "Number of commits : $numcommits"
              echo ::set-env name=TEST_VAR::true
              if [ $numcommits -gt 0 ]; then
                echo ::set-env name=UPDATES::true
              fi
      - name:  Test testvar
        if:    env.TEST_VAR == 'true'
        run:   echo "Test var is true"
        shell: bash
      - name:  Test updates var
        if:    env.UPDATES == 'true'
        run:   echo "UPDATES var is true"
        shell: bash
