name: Test Workflow
env:
  TEST: this is a test variable

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  job_1:
    runs-on: macos-latest
    name: Get Date Yesterday
    steps:
      - name: See if the date command works
        shell: bash
        run: |
          date -v -1d -u +'%FT%T.%2NZ' 
      - name: Get commits save as var
        shell: bash
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
              curl -sL "https://api.github.com/repos/$GITHUB_REPOSITORY/commits" > $HOME/commit.json
              echo $(head -n 10 $HOME/commit.json)
              numcommits="$(jq '. | length' $HOME/commit.json)"
              echo "Number of commits : $numcommits"
              echo ::set-env name=TEST_VAR::true
              if [ $numcommits -gt 0 ]; then
                echo ::set-env name=UPDATES::true
              fi
      - name:  Test testvar
        if:    env.TEST_VAR == 'true'
        run:   echo "Test var is true"
        shell: bash
      - name:  Test updates var
        if:    env.UPDATES == 'true'
        run:   echo "UPDATES var is true"
        shell: bash

  
